"""
Django settings for bopo_backend project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
# from dotenv import load_dotenv

# load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5+1e)3&p(_v%xx@oaugfu&f51l=7l*=^#r0@*p*4%^vbilr0po'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bopo_admin',
    'bopo_award',
    'bopo',    # 'bopo_customer',
    'accounts',
    'transaction_history',
    'rest_framework',
    'corsheaders',
    'qr_store', 
    'transfer',
    
    'channels',
    
    
]

CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'bopo_admin.middleware.CorporateStatusCheckMiddleware', 
]

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'access-control-allow-origin',
]


CSRF_TRUSTED_ORIGINS = [
    "https://8e09-103-211-60-165.ngrok-free.app",
    "https://3fb0-2401-4900-79d1-d74-6851-4650-8615-f92c.ngrok-free.app",
    "https://7a22-2401-4900-57c6-ae7c-e933-a11b-70e7-85f4.ngrok-free.app",
]




ALLOWED_HOSTS = ['*']

ROOT_URLCONF = 'bopo_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'bopo_admin.context_processors.employee_permissions',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.logo_context',  
            ],
        },
    },
]

# WSGI_APPLICATION = 'bopo_backend.wsgi.application'
ASGI_APPLICATION = "bopo_backend.routing.application"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],    #6379
        },
    },
}

# Timezone settings
USE_TZ = True  # This enables time zone support
TIME_ZONE = 'Asia/Kolkata'  # Set your preferred timezone (replace if needed)
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
    
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'my_django_db',
#         'USER': 'django_user',
#         'PASSWORD': 'NewPassword',
#         'HOST': 'localhost',  # Or IP if remote DB # or '127.0.0.1'
#         'PORT': '3305',
#     }
# }

DEBUG = os.getenv("DEBUG", "False") == "True"
# SECRET_KEY = os.getenv("SECRET_KEY")

# Database example (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'bopo_admin.BopoAdmin'
LOGIN_URL = '/login/'

# Twilio Configuration
TWILIO_ACCOUNT_SID = "ACefc2b57333c60eaaea16e2ba775ade3c"
TWILIO_AUTH_TOKEN = "1f74c22a0c836453ae608e6a37a1e965"
TWILIO_PHONE_NUMBER = "+12706338124"


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# Media files (Uploaded files)
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Ensure STATICFILES_DIRS points to existing directories
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Ensure this directory exists
]
