services:
  web:
    build: .
    command: "daphne -b 0.0.0.0 -p 8000 bopo_backend.asgi:application"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app 
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"